// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc/calc_proto/calc.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindMaxRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxRequest) Reset()         { *m = FindMaxRequest{} }
func (m *FindMaxRequest) String() string { return proto.CompactTextString(m) }
func (*FindMaxRequest) ProtoMessage()    {}
func (*FindMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{0}
}

func (m *FindMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxRequest.Unmarshal(m, b)
}
func (m *FindMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxRequest.Marshal(b, m, deterministic)
}
func (m *FindMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxRequest.Merge(m, src)
}
func (m *FindMaxRequest) XXX_Size() int {
	return xxx_messageInfo_FindMaxRequest.Size(m)
}
func (m *FindMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxRequest proto.InternalMessageInfo

func (m *FindMaxRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FindMaxResponse struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxResponse) Reset()         { *m = FindMaxResponse{} }
func (m *FindMaxResponse) String() string { return proto.CompactTextString(m) }
func (*FindMaxResponse) ProtoMessage()    {}
func (*FindMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{1}
}

func (m *FindMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxResponse.Unmarshal(m, b)
}
func (m *FindMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxResponse.Marshal(b, m, deterministic)
}
func (m *FindMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxResponse.Merge(m, src)
}
func (m *FindMaxResponse) XXX_Size() int {
	return xxx_messageInfo_FindMaxResponse.Size(m)
}
func (m *FindMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxResponse proto.InternalMessageInfo

func (m *FindMaxResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CalculateAverageRequest struct {
	Number               float64  `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateAverageRequest) Reset()         { *m = CalculateAverageRequest{} }
func (m *CalculateAverageRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateAverageRequest) ProtoMessage()    {}
func (*CalculateAverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{2}
}

func (m *CalculateAverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateAverageRequest.Unmarshal(m, b)
}
func (m *CalculateAverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateAverageRequest.Marshal(b, m, deterministic)
}
func (m *CalculateAverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateAverageRequest.Merge(m, src)
}
func (m *CalculateAverageRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateAverageRequest.Size(m)
}
func (m *CalculateAverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateAverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateAverageRequest proto.InternalMessageInfo

func (m *CalculateAverageRequest) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CalculateAverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateAverageResponse) Reset()         { *m = CalculateAverageResponse{} }
func (m *CalculateAverageResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateAverageResponse) ProtoMessage()    {}
func (*CalculateAverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{3}
}

func (m *CalculateAverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateAverageResponse.Unmarshal(m, b)
}
func (m *CalculateAverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateAverageResponse.Marshal(b, m, deterministic)
}
func (m *CalculateAverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateAverageResponse.Merge(m, src)
}
func (m *CalculateAverageResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateAverageResponse.Size(m)
}
func (m *CalculateAverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateAverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateAverageResponse proto.InternalMessageInfo

func (m *CalculateAverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

type CalculateSumRequest struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateSumRequest) Reset()         { *m = CalculateSumRequest{} }
func (m *CalculateSumRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateSumRequest) ProtoMessage()    {}
func (*CalculateSumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{4}
}

func (m *CalculateSumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateSumRequest.Unmarshal(m, b)
}
func (m *CalculateSumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateSumRequest.Marshal(b, m, deterministic)
}
func (m *CalculateSumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateSumRequest.Merge(m, src)
}
func (m *CalculateSumRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateSumRequest.Size(m)
}
func (m *CalculateSumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateSumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateSumRequest proto.InternalMessageInfo

func (m *CalculateSumRequest) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CalculateSumRequest) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type CalculateSumResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateSumResponse) Reset()         { *m = CalculateSumResponse{} }
func (m *CalculateSumResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateSumResponse) ProtoMessage()    {}
func (*CalculateSumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{5}
}

func (m *CalculateSumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateSumResponse.Unmarshal(m, b)
}
func (m *CalculateSumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateSumResponse.Marshal(b, m, deterministic)
}
func (m *CalculateSumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateSumResponse.Merge(m, src)
}
func (m *CalculateSumResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateSumResponse.Size(m)
}
func (m *CalculateSumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateSumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateSumResponse proto.InternalMessageInfo

func (m *CalculateSumResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeDecomposeRequest struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeDecomposeRequest) Reset()         { *m = PrimeDecomposeRequest{} }
func (m *PrimeDecomposeRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeDecomposeRequest) ProtoMessage()    {}
func (*PrimeDecomposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{6}
}

func (m *PrimeDecomposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeDecomposeRequest.Unmarshal(m, b)
}
func (m *PrimeDecomposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeDecomposeRequest.Marshal(b, m, deterministic)
}
func (m *PrimeDecomposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeDecomposeRequest.Merge(m, src)
}
func (m *PrimeDecomposeRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeDecomposeRequest.Size(m)
}
func (m *PrimeDecomposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeDecomposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeDecomposeRequest proto.InternalMessageInfo

func (m *PrimeDecomposeRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeDecomposeResponse struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeDecomposeResponse) Reset()         { *m = PrimeDecomposeResponse{} }
func (m *PrimeDecomposeResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeDecomposeResponse) ProtoMessage()    {}
func (*PrimeDecomposeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62affd3053f75dd3, []int{7}
}

func (m *PrimeDecomposeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeDecomposeResponse.Unmarshal(m, b)
}
func (m *PrimeDecomposeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeDecomposeResponse.Marshal(b, m, deterministic)
}
func (m *PrimeDecomposeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeDecomposeResponse.Merge(m, src)
}
func (m *PrimeDecomposeResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeDecomposeResponse.Size(m)
}
func (m *PrimeDecomposeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeDecomposeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeDecomposeResponse proto.InternalMessageInfo

func (m *PrimeDecomposeResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*FindMaxRequest)(nil), "calc.FindMaxRequest")
	proto.RegisterType((*FindMaxResponse)(nil), "calc.FindMaxResponse")
	proto.RegisterType((*CalculateAverageRequest)(nil), "calc.CalculateAverageRequest")
	proto.RegisterType((*CalculateAverageResponse)(nil), "calc.CalculateAverageResponse")
	proto.RegisterType((*CalculateSumRequest)(nil), "calc.CalculateSumRequest")
	proto.RegisterType((*CalculateSumResponse)(nil), "calc.CalculateSumResponse")
	proto.RegisterType((*PrimeDecomposeRequest)(nil), "calc.PrimeDecomposeRequest")
	proto.RegisterType((*PrimeDecomposeResponse)(nil), "calc.PrimeDecomposeResponse")
}

func init() { proto.RegisterFile("calc/calc_proto/calc.proto", fileDescriptor_62affd3053f75dd3) }

var fileDescriptor_62affd3053f75dd3 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x76, 0xd1, 0x00, 0x99, 0x20, 0x9a, 0xe5, 0xc7, 0xba, 0xa2, 0x31, 0x7b, 0x42, 0x0f, 0x14,
	0xd4, 0x93, 0xf1, 0xe2, 0x4f, 0xbc, 0x19, 0x0d, 0xc6, 0x0b, 0x17, 0xb3, 0xd4, 0x09, 0x69, 0xd2,
	0x76, 0x6b, 0x7f, 0x08, 0x5c, 0x7d, 0x05, 0xdf, 0xcb, 0x8b, 0xaf, 0xe0, 0x83, 0x98, 0x76, 0x5b,
	0xb0, 0xb5, 0xe8, 0x65, 0x33, 0xdf, 0xce, 0x7c, 0x33, 0xdf, 0xec, 0x7e, 0xc0, 0x0c, 0x61, 0x19,
	0x7a, 0x74, 0x3c, 0xbb, 0x9e, 0x0c, 0x64, 0x1c, 0xf6, 0xe2, 0x90, 0x6e, 0x44, 0x31, 0xeb, 0x4c,
	0xa4, 0x9c, 0x58, 0xa8, 0x0b, 0xd7, 0xd4, 0x85, 0xe3, 0xc8, 0x40, 0x04, 0xa6, 0x74, 0x7c, 0x55,
	0xc3, 0xbb, 0x50, 0xbf, 0x35, 0x9d, 0x97, 0x3b, 0x31, 0x1b, 0xe2, 0x6b, 0x88, 0x7e, 0x40, 0xdb,
	0x50, 0x76, 0x42, 0x7b, 0x8c, 0x9e, 0x46, 0x0e, 0x49, 0x77, 0x7d, 0x98, 0x20, 0x7e, 0x04, 0x5b,
	0x8b, 0x4a, 0xdf, 0x95, 0x8e, 0x8f, 0x2b, 0x4b, 0x07, 0xb0, 0x73, 0x2d, 0x2c, 0x23, 0xb4, 0x44,
	0x80, 0x97, 0x53, 0xf4, 0xc4, 0x04, 0x8b, 0xbb, 0x93, 0x05, 0xe5, 0x0c, 0xb4, 0xdf, 0x94, 0x64,
	0x8c, 0x06, 0x15, 0xa1, 0xae, 0x12, 0x52, 0x0a, 0xf9, 0x00, 0x1a, 0x0b, 0xd6, 0x63, 0x68, 0xa7,
	0x43, 0x6a, 0x40, 0x66, 0x89, 0x24, 0x32, 0x8b, 0xd0, 0x5c, 0x2b, 0x29, 0x34, 0xe7, 0x3d, 0x68,
	0x66, 0x29, 0xcb, 0x5d, 0x3c, 0xf4, 0x43, 0x2b, 0x48, 0x77, 0x51, 0x88, 0xeb, 0xd0, 0x7a, 0xf0,
	0x4c, 0x1b, 0x6f, 0xd0, 0x90, 0xb6, 0x2b, 0x7d, 0xfc, 0xef, 0x9d, 0xfa, 0xd0, 0xce, 0x13, 0xfe,
	0x7e, 0xae, 0x93, 0x8f, 0x12, 0x40, 0xaa, 0x49, 0x7a, 0x74, 0x04, 0xb5, 0x9f, 0x0a, 0xe9, 0x6e,
	0x2f, 0xfe, 0xd3, 0x82, 0x45, 0x19, 0x2b, 0x4a, 0xa9, 0x69, 0xbc, 0xf1, 0xf6, 0xf9, 0xf5, 0x5e,
	0xda, 0xe4, 0x55, 0x7d, 0x3a, 0x88, 0x5d, 0x71, 0x4e, 0x8e, 0xe9, 0x3d, 0xd4, 0xb3, 0xe2, 0xe8,
	0x9e, 0x6a, 0x51, 0xb8, 0x23, 0xeb, 0x14, 0x27, 0x93, 0x09, 0x6b, 0x7d, 0x42, 0x9f, 0x60, 0x3b,
	0xff, 0x6f, 0x74, 0x3f, 0xa7, 0x2a, 0x6b, 0x01, 0x76, 0xb0, 0x2a, 0x9d, 0xb6, 0xed, 0x12, 0x7a,
	0x01, 0x95, 0xc4, 0x6c, 0xb4, 0xa9, 0xca, 0xb3, 0x2e, 0x65, 0xad, 0xdc, 0xed, 0x92, 0xdb, 0x27,
	0x57, 0xd5, 0x51, 0x39, 0xca, 0xba, 0xe3, 0x71, 0x39, 0x76, 0xf9, 0xe9, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x21, 0xe2, 0x49, 0x1d, 0x27, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorClient interface {
	// Unary
	CalculateSum(ctx context.Context, in *CalculateSumRequest, opts ...grpc.CallOption) (*CalculateSumResponse, error)
	// Server stream
	PrimeDecompose(ctx context.Context, in *PrimeDecomposeRequest, opts ...grpc.CallOption) (Calculator_PrimeDecomposeClient, error)
	// Client stream
	CalculateAverage(ctx context.Context, opts ...grpc.CallOption) (Calculator_CalculateAverageClient, error)
	// Bi-directional stream
	FindMax(ctx context.Context, opts ...grpc.CallOption) (Calculator_FindMaxClient, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) CalculateSum(ctx context.Context, in *CalculateSumRequest, opts ...grpc.CallOption) (*CalculateSumResponse, error) {
	out := new(CalculateSumResponse)
	err := c.cc.Invoke(ctx, "/calc.Calculator/CalculateSum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) PrimeDecompose(ctx context.Context, in *PrimeDecomposeRequest, opts ...grpc.CallOption) (Calculator_PrimeDecomposeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[0], "/calc.Calculator/PrimeDecompose", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorPrimeDecomposeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Calculator_PrimeDecomposeClient interface {
	Recv() (*PrimeDecomposeResponse, error)
	grpc.ClientStream
}

type calculatorPrimeDecomposeClient struct {
	grpc.ClientStream
}

func (x *calculatorPrimeDecomposeClient) Recv() (*PrimeDecomposeResponse, error) {
	m := new(PrimeDecomposeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorClient) CalculateAverage(ctx context.Context, opts ...grpc.CallOption) (Calculator_CalculateAverageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[1], "/calc.Calculator/CalculateAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorCalculateAverageClient{stream}
	return x, nil
}

type Calculator_CalculateAverageClient interface {
	Send(*CalculateAverageRequest) error
	CloseAndRecv() (*CalculateAverageResponse, error)
	grpc.ClientStream
}

type calculatorCalculateAverageClient struct {
	grpc.ClientStream
}

func (x *calculatorCalculateAverageClient) Send(m *CalculateAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorCalculateAverageClient) CloseAndRecv() (*CalculateAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CalculateAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorClient) FindMax(ctx context.Context, opts ...grpc.CallOption) (Calculator_FindMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Calculator_serviceDesc.Streams[2], "/calc.Calculator/FindMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorFindMaxClient{stream}
	return x, nil
}

type Calculator_FindMaxClient interface {
	Send(*FindMaxRequest) error
	Recv() (*FindMaxResponse, error)
	grpc.ClientStream
}

type calculatorFindMaxClient struct {
	grpc.ClientStream
}

func (x *calculatorFindMaxClient) Send(m *FindMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorFindMaxClient) Recv() (*FindMaxResponse, error) {
	m := new(FindMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServer is the server API for Calculator service.
type CalculatorServer interface {
	// Unary
	CalculateSum(context.Context, *CalculateSumRequest) (*CalculateSumResponse, error)
	// Server stream
	PrimeDecompose(*PrimeDecomposeRequest, Calculator_PrimeDecomposeServer) error
	// Client stream
	CalculateAverage(Calculator_CalculateAverageServer) error
	// Bi-directional stream
	FindMax(Calculator_FindMaxServer) error
}

// UnimplementedCalculatorServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (*UnimplementedCalculatorServer) CalculateSum(ctx context.Context, req *CalculateSumRequest) (*CalculateSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSum not implemented")
}
func (*UnimplementedCalculatorServer) PrimeDecompose(req *PrimeDecomposeRequest, srv Calculator_PrimeDecomposeServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeDecompose not implemented")
}
func (*UnimplementedCalculatorServer) CalculateAverage(srv Calculator_CalculateAverageServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateAverage not implemented")
}
func (*UnimplementedCalculatorServer) FindMax(srv Calculator_FindMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMax not implemented")
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_CalculateSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).CalculateSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calculator/CalculateSum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).CalculateSum(ctx, req.(*CalculateSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_PrimeDecompose_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeDecomposeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServer).PrimeDecompose(m, &calculatorPrimeDecomposeServer{stream})
}

type Calculator_PrimeDecomposeServer interface {
	Send(*PrimeDecomposeResponse) error
	grpc.ServerStream
}

type calculatorPrimeDecomposeServer struct {
	grpc.ServerStream
}

func (x *calculatorPrimeDecomposeServer) Send(m *PrimeDecomposeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Calculator_CalculateAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).CalculateAverage(&calculatorCalculateAverageServer{stream})
}

type Calculator_CalculateAverageServer interface {
	SendAndClose(*CalculateAverageResponse) error
	Recv() (*CalculateAverageRequest, error)
	grpc.ServerStream
}

type calculatorCalculateAverageServer struct {
	grpc.ServerStream
}

func (x *calculatorCalculateAverageServer) SendAndClose(m *CalculateAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorCalculateAverageServer) Recv() (*CalculateAverageRequest, error) {
	m := new(CalculateAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Calculator_FindMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServer).FindMax(&calculatorFindMaxServer{stream})
}

type Calculator_FindMaxServer interface {
	Send(*FindMaxResponse) error
	Recv() (*FindMaxRequest, error)
	grpc.ServerStream
}

type calculatorFindMaxServer struct {
	grpc.ServerStream
}

func (x *calculatorFindMaxServer) Send(m *FindMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorFindMaxServer) Recv() (*FindMaxRequest, error) {
	m := new(FindMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateSum",
			Handler:    _Calculator_CalculateSum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecompose",
			Handler:       _Calculator_PrimeDecompose_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CalculateAverage",
			Handler:       _Calculator_CalculateAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMax",
			Handler:       _Calculator_FindMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calc/calc_proto/calc.proto",
}
